<?php

/**
 * Created by PhpStorm.
 * User: eValor
 * Date: 2018/11/14
 * Time: 上午9:09
 */

namespace PHPSTORM_META {

    override(\pc_base::load_model(0), map([
        'admin_model'              => \admin_model::class,
        'admin_panel_model'        => \admin_panel_model::class,
        'admin_role_model'         => \admin_role_model::class,
        'admin_role_priv_model'    => \admin_role_priv_model::class,
        'announce_model'           => \announce_model::class,
        'attachment_index_model'   => \attachment_index_model::class,
        'attachment_model'         => \attachment_model::class,
        'badword_model'            => \badword_model::class,
        'block_history_model'      => \block_history_model::class,
        'block_model'              => \block_model::class,
        'block_priv_model'         => \block_priv_model::class,
        'cache_model'              => \cache_model::class,
        'category_model'           => \category_model::class,
        'category_priv_model'      => \category_priv_model::class,
        'collection_content_model' => \collection_content_model::class,
        'collection_history_model' => \collection_history_model::class,
        'collection_node_model'    => \collection_node_model::class,
        'collection_program_model' => \collection_program_model::class,
        'comment_check_model'      => \comment_check_model::class,
        'comment_data_model'       => \comment_data_model::class,
        'comment_model'            => \comment_model::class,
        'comment_setting_model'    => \comment_setting_model::class,
        'comment_table_model'      => \comment_table_model::class,
        'content_check_model'      => \content_check_model::class,
        'content_model'            => \content_model::class,
        'copyfrom_model'           => \copyfrom_model::class,
        'datacall_model'           => \datacall_model::class,
        'dbsource_model'           => \dbsource_model::class,
        'dianping_data_model'      => \dianping_data_model::class,
        'dianping_model'           => \dianping_model::class,
        'dianping_type_model'      => \dianping_type_model::class,
        'downservers_model'        => \downservers_model::class,
        'extend_setting_model'     => \extend_setting_model::class,
        'favorite_model'           => \favorite_model::class,
        'friend_model'             => \friend_model::class,
        'get_model'                => \get_model::class,
        'googlesitemap_item_model' => \googlesitemap_item_model::class,
        'googlesitemap_model'      => \googlesitemap_model::class,
        'hits_model'               => \hits_model::class,
        'index.html'               => \index . html::class,
        'ipbanned_model'           => \ipbanned_model::class,
        'keylink_model'            => \keylink_model::class,
        'keyword_data_model'       => \keyword_data_model::class,
        'keyword_model'            => \keyword_model::class,
        'link_model'               => \link_model::class,
        'linkage_model'            => \linkage_model::class,
        'log_model'                => \log_model::class,
        'maillist_model'           => \maillist_model::class,
        'member_group_model'       => \member_group_model::class,
        'member_menu_model'        => \member_menu_model::class,
        'member_model'             => \member_model::class,
        'member_model_model'       => \member_model_model::class,
        'member_point_model'       => \member_point_model::class,
        'member_verify_model'      => \member_verify_model::class,
        'members_model'            => \members_model::class,
        'menu_model'               => \menu_model::class,
        'message_data_model'       => \message_data_model::class,
        'message_group_model'      => \message_group_model::class,
        'message_model'            => \message_model::class,
        'module_model'             => \module_model::class,
        'mood_model'               => \mood_model::class,
        'page_model'               => \page_model::class,
        'pay_account_model'        => \pay_account_model::class,
        'pay_payment_model'        => \pay_payment_model::class,
        'pay_spend_model'          => \pay_spend_model::class,
        'plugin_model'             => \plugin_model::class,
        'plugin_var_model'         => \plugin_var_model::class,
        'position_data_model'      => \position_data_model::class,
        'position_model'           => \position_model::class,
        'poster_model'             => \poster_model::class,
        'poster_space_model'       => \poster_space_model::class,
        'poster_stat_model'        => \poster_stat_model::class,
        'ps_members_model'         => \ps_members_model::class,
        'queue_model'              => \queue_model::class,
        'release_point_model'      => \release_point_model::class,
        'search_keyword_model'     => \search_keyword_model::class,
        'search_model'             => \search_model::class,
        'session_model'            => \session_model::class,
        'site_model'               => \site_model::class,
        'sitemodel_field_model'    => \sitemodel_field_model::class,
        'sitemodel_model'          => \sitemodel_model::class,
        'sms_report_model'         => \sms_report_model::class,
        'special_c_data_model'     => \special_c_data_model::class,
        'special_content_model'    => \special_content_model::class,
        'special_model'            => \special_model::class,
        'sso_members_model'        => \sso_members_model::class,
        'tag_model'                => \tag_model::class,
        'template_bak_model'       => \template_bak_model::class,
        'times_model'              => \times_model::class,
        'type_model'               => \type_model::class,
        'urlrule_model'            => \urlrule_model::class,
        'video_content_model'      => \video_content_model::class,
        'video_store_model'        => \video_store_model::class,
        'vote_data_model'          => \vote_data_model::class,
        'vote_option_model'        => \vote_option_model::class,
        'vote_subject_model'       => \vote_subject_model::class,
        'wap_model'                => \wap_model::class,
        'wap_type_model'           => \wap_type_model::class,
        'workflow_model'           => \workflow_model::class

    ]));

}